"use client";

/**
 * RollbackBuilder — interactive form that produces a printable rollback runbook.
 *
 * - All client-side (no data leaves the browser)
 * - Persists draft to localStorage as `sad:rollback-draft`
 * - Copy to clipboard, print stylesheet, downloadable .md
 */

import { useEffect, useState } from "react";

type Draft = {
  changeName: string;
  changedAt: string;
  flagOrSwitch: string;
  rollbackCommand: string;
  verifyCommand: string;
  pageWho: string;
  knownBlastRadius: string;
};

const EMPTY: Draft = {
  changeName: "",
  changedAt: "",
  flagOrSwitch: "",
  rollbackCommand: "",
  verifyCommand: "",
  pageWho: "",
  knownBlastRadius: "",
};

const EXAMPLE: Draft = {
  changeName: "Enable new pricing page experiment (variant B)",
  changedAt: new Date().toISOString().slice(0, 16),
  flagOrSwitch: "LaunchDarkly flag: pricing_page_v2",
  rollbackCommand:
    "ld flag-toggle pricing_page_v2 --env prod --off\n# OR via UI: launchdarkly.com → Production → pricing_page_v2 → toggle off",
  verifyCommand:
    "curl -s https://sageideas.dev/api/health/pricing | jq '.variant'\n# expect: \"control\"",
  pageWho:
    "@jason in #incidents (primary)\n@oncall in #platform (secondary, after 5min)",
  knownBlastRadius:
    "Pricing page only. No effect on signup, checkout, or auth.\nNo DB writes. Fully reversible in <10s.",
};

const STORAGE_KEY = "sad:rollback-draft";

function buildRunbook(d: Draft): string {
  const stamp = d.changedAt
    ? new Date(d.changedAt).toISOString().replace("T", " ").slice(0, 16) + " UTC"
    : "[fill in time]";
  return `# 30-SECOND ROLLBACK
> Generated by sageafterdark.com/tools/30-second-rollback

## Change
${d.changeName || "[name your change]"}

## When deployed
${stamp}

## Kill switch
${d.flagOrSwitch || "[where is the kill switch]"}

## Rollback command (copy/paste)
\`\`\`
${d.rollbackCommand || "[exact command to reverse]"}
\`\`\`

## Verify rolled back
\`\`\`
${d.verifyCommand || "[command/URL that proves it]"}
\`\`\`

## If it doesn't work, page
${d.pageWho || "[who to ping, in what channel, in what order]"}

## Known blast radius
${d.knownBlastRadius || "[what this affects, what it doesn't]"}

---
Print this. Tape it next to the deploy button.
`;
}

export function RollbackBuilder() {
  const [draft, setDraft] = useState<Draft>(EMPTY);
  const [copied, setCopied] = useState(false);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) setDraft({ ...EMPTY, ...JSON.parse(raw) });
    } catch {}
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(draft));
    } catch {}
  }, [draft, hydrated]);

  const update = <K extends keyof Draft>(k: K) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => setDraft((d) => ({ ...d, [k]: e.target.value }));

  const runbook = buildRunbook(draft);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(runbook);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {}
  };

  const download = () => {
    const blob = new Blob([runbook], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "rollback-runbook.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const print = () => window.print();

  const reset = () => {
    if (confirm("Clear the form?")) setDraft(EMPTY);
  };

  const loadExample = () => setDraft(EXAMPLE);

  return (
    <div className="grid gap-8 lg:grid-cols-2">
      {/* FORM */}
      <form
        className="space-y-5 print:hidden"
        onSubmit={(e) => e.preventDefault()}
        aria-label="Rollback runbook builder"
      >
        <div className="flex items-center justify-between">
          <h2 className="font-display text-xl">Inputs</h2>
          <button
            type="button"
            onClick={loadExample}
            className="text-xs uppercase tracking-wider text-cyan hover:underline"
          >
            Load example
          </button>
        </div>

        <Field
          label="What did you change?"
          hint="One line. Plain English."
          value={draft.changeName}
          onChange={update("changeName")}
          placeholder="e.g. Enable new pricing page experiment"
        />
        <Field
          label="When did it deploy?"
          type="datetime-local"
          value={draft.changedAt}
          onChange={update("changedAt")}
        />
        <Field
          label="Where is the kill switch?"
          hint="Flag name, env var, deploy ID — whatever flips it back."
          value={draft.flagOrSwitch}
          onChange={update("flagOrSwitch")}
          placeholder="e.g. LaunchDarkly flag: pricing_page_v2"
        />
        <FieldArea
          label="Rollback command"
          hint="The exact command. Multiple lines OK."
          value={draft.rollbackCommand}
          onChange={update("rollbackCommand")}
          placeholder="ld flag-toggle pricing_page_v2 --env prod --off"
          rows={3}
        />
        <FieldArea
          label="How will you verify it rolled back?"
          hint="A curl, a SQL check, a URL — proof, not vibes."
          value={draft.verifyCommand}
          onChange={update("verifyCommand")}
          placeholder='curl -s https://app.example.com/health | jq .variant'
          rows={3}
        />
        <FieldArea
          label="If it doesn't work, page who?"
          hint="In what channel. In what order."
          value={draft.pageWho}
          onChange={update("pageWho")}
          placeholder="@oncall in #incidents (primary)"
          rows={2}
        />
        <FieldArea
          label="Known blast radius"
          hint="What does this affect? What doesn't it touch?"
          value={draft.knownBlastRadius}
          onChange={update("knownBlastRadius")}
          placeholder="Pricing page only. No DB writes."
          rows={3}
        />

        <div className="flex flex-wrap gap-3 pt-2">
          <button
            type="button"
            onClick={copy}
            className="px-4 py-2 bg-cyan text-ink-0 uppercase tracking-wider text-xs font-display hover:bg-cyan/90 transition-colors"
          >
            {copied ? "Copied!" : "Copy runbook"}
          </button>
          <button
            type="button"
            onClick={download}
            className="px-4 py-2 border border-rule-hi uppercase tracking-wider text-xs font-display hover:border-cyan hover:text-cyan transition-colors"
          >
            Download .md
          </button>
          <button
            type="button"
            onClick={print}
            className="px-4 py-2 border border-rule-hi uppercase tracking-wider text-xs font-display hover:border-cyan hover:text-cyan transition-colors"
          >
            Print
          </button>
          <button
            type="button"
            onClick={reset}
            className="px-4 py-2 text-xs uppercase tracking-wider text-mute hover:text-cyan transition-colors"
          >
            Reset
          </button>
        </div>
      </form>

      {/* PREVIEW */}
      <div className="lg:sticky lg:top-24 self-start">
        <h2 className="font-display text-xl mb-4 print:hidden">Runbook preview</h2>
        <pre className="p-6 bg-ink-1 border border-rule text-sm font-mono whitespace-pre-wrap leading-relaxed overflow-auto max-h-[70vh] print:max-h-none print:border-0 print:bg-transparent print:p-0 text-bone">
          {runbook}
        </pre>
      </div>
    </div>
  );
}

function Field(props: {
  label: string;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  placeholder?: string;
  hint?: string;
  type?: string;
}) {
  return (
    <label className="block">
      <span className="block font-display text-sm mb-1">{props.label}</span>
      {props.hint && (
        <span className="block text-xs text-mute mb-2">{props.hint}</span>
      )}
      <input
        type={props.type ?? "text"}
        value={props.value}
        onChange={props.onChange}
        placeholder={props.placeholder}
        className="w-full px-3 py-2 bg-ink-1 border border-rule focus:border-cyan focus:outline-none font-mono text-sm text-bone"
      />
    </label>
  );
}

function FieldArea(props: {
  label: string;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
  placeholder?: string;
  hint?: string;
  rows?: number;
}) {
  return (
    <label className="block">
      <span className="block font-display text-sm mb-1">{props.label}</span>
      {props.hint && (
        <span className="block text-xs text-mute mb-2">{props.hint}</span>
      )}
      <textarea
        value={props.value}
        onChange={props.onChange}
        placeholder={props.placeholder}
        rows={props.rows ?? 3}
        className="w-full px-3 py-2 bg-ink-1 border border-rule focus:border-cyan focus:outline-none font-mono text-sm resize-y text-bone"
      />
    </label>
  );
}
